# Generated by Django 4.0.6 on 2022-08-24 14:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('db', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='director',
            old_name='count',
            new_name='country',
        ),
    ]
