# Generated by Django 3.2.13 on 2022-10-06 05:04

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Movie',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=20, verbose_name='제목')),
                ('summary', models.TextField(verbose_name='줄거리')),
                ('running_time', models.IntegerField(verbose_name='러닝타임')),
            ],
        ),
    ]
